name: od_photo
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

# ----- PACKAGES ----- #
dependencies:
  flutter:
    sdk: flutter

# Utility Packages
  http: ^1.1.0
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.6
  shared_preferences: ^2.0.8
  flutter_svg: ^2.0.9

# Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

# ----- ./ PACKEGES END ----- #

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # ----- LOCAL ASSESTS ----- #
  assets:
    - assets/images/
    - assets/icons/


  # ----- LOCAL FONTS ----- #
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 800
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 800
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
